### Hi there ğŸ‘‹

My name is **Luca David** and I am a graduate student ğŸ‘¨ğŸ¼â€ğŸ“ in Economics and Finance at the University of TÃ¼bingen ğŸ‡©ğŸ‡ª and the UniversitÃ  degli studi di Pavia ğŸ‡®ğŸ‡¹.

Short bio:

ğŸ’¯ &emsp;  2017-2021: &emsp;  Mathematics and Management (B.Sc.), Ulm University                       ğŸ‡©ğŸ‡ª <br />
ğŸ§  &emsp;  2017-2022: &emsp;  Psychology (B.Sc.), Ulm University                                       ğŸ‡©ğŸ‡ª <br />
â†—ï¸ &emsp;  2021-2023: &emsp;  Economics (M.Sc.), Eberhard Karls University of TÃ¼bingen                 ğŸ‡©ğŸ‡ª <br />
ğŸ¦ &emsp;  2022-2023: &emsp;  Economics and Finance (dott. mag.), UniversitÃ  degli studi di Pavia      ğŸ‡®ğŸ‡¹ <br />

<!---
since 2023: Ph.D. Student in Applied Microeconomics, Ulm University
-->

Research Interests:

* Experimental and Behavioral Economics   <br />
* Microeconometrics                       <br />
* Sport Economics                         <br />

<!---
Sprechstunde: nach Vereinbarung 
-->

Here are some ideas to get you started:

- ğŸ”­ Iâ€™m currently working on ...
- ğŸŒ± Iâ€™m currently learning ...
- ğŸ‘¯ Iâ€™m looking to collaborate on ...
- ğŸ¤” Iâ€™m looking for help with ...
- ğŸ’¬ Ask me about ...
- ğŸ“« How to reach me: ...
- ğŸ˜„ Pronouns: ...
- âš¡ Fun fact: ...
